CREATE TABLE IF NOT EXISTS country(
name VARCHAR(200) NOT NULL UNIQUE,
id INTEGER PRIMARY KEY,
capital VARCHAR(200) NOT NULL,
region VARCHAR(200) NOT NULL,
sub-region VARCHAR(200) NOT NULL,
area DOUBLE NOT NULL
)